scripts: shfmt-ify
* shfmt -w -s -i=4

Signed-off-by: Albert I <kras@raphielgang.org>

diff --git a/snippets/tg_sendinline b/snippets/tg_sendinline
--- a/snippets/tg_sendinline
+++ b/snippets/tg_sendinline
@@ -12,40 +12,57 @@ tg_sendinline() {
     # Parse parameters
     while [[ $# -ge 1 ]]; do
         case $1 in
-            # REQUIRED
-            -in |--inline-name) shift
-                INLINE_TEXT=$1 ;;
+        # REQUIRED
+        -in | --inline-name)
+            shift
+            INLINE_TEXT=$1
+            ;;
 
-            -inr|--inline-name-row) shift
-                INLINE_TEXT=$1
-                ON_SAME_ROW=true ;;
+        -inr | --inline-name-row)
+            shift
+            INLINE_TEXT=$1
+            ON_SAME_ROW=true
+            ;;
 
-            -iu |--inline-url) shift
-                INLINE_URL=$1 ;;
+        -iu | --inline-url)
+            shift
+            INLINE_URL=$1
+            ;;
 
-            -iur|--inline-url-row) shift
-                INLINE_URL=$1
-                ON_SAME_ROW=true ;;
+        -iur | --inline-url-row)
+            shift
+            INLINE_URL=$1
+            ON_SAME_ROW=true
+            ;;
 
-            # REQUIRED, BUT CAN BE SET EXTERNALLY
-            -c  |--chat-id) shift
-                local TELEGRAM_CHAT
-                TELEGRAM_CHAT=$1 ;;
+        # REQUIRED, BUT CAN BE SET EXTERNALLY
+        -c | --chat-id)
+            shift
+            local TELEGRAM_CHAT
+            TELEGRAM_CHAT=$1
+            ;;
 
-            -t  |--token) shift
-                [[ $1 != *:* ]] && { warn "Invalid value specified!"; return 1; }
-                local TELEGRAM_TOKEN
-                TELEGRAM_TOKEN=$1 ;;
+        -t | --token)
+            shift
+            [[ $1 != *:* ]] && {
+                warn "Invalid value specified!"
+                return 1
+            }
+            local TELEGRAM_TOKEN
+            TELEGRAM_TOKEN=$1
+            ;;
 
-            # OPTIONAL
-            -b  |--break)
-                INLINE+="
+        # OPTIONAL
+        -b | --break)
+            INLINE+="
             ],"
-                unset ROW_COUNT ;;
+            unset ROW_COUNT
+            ;;
 
-            # EVERYTHING ELSE: Send as part of message instead
-            *)
-                TEXT+="$1\n" ;;
+        # EVERYTHING ELSE: Send as part of message instead
+        *)
+            TEXT+="$1\n"
+            ;;
         esac
         shift
 
@@ -64,7 +81,7 @@ tg_sendinline() {
                 fi
                 [[ -z $COUNT ]] && COUNT=1 || COUNT=$((COUNT + 1))
             fi
-            [[ -z $ROW_COUNT || ( $ROW_COUNT = 1 && -n $ON_SAME_ROW ) ]] && INLINE+="
+            [[ -z $ROW_COUNT || ($ROW_COUNT == 1 && -n $ON_SAME_ROW) ]] && INLINE+="
             [
                 {" || INLINE+="
                 {"
@@ -90,7 +107,7 @@ tg_sendinline() {
     fi
 
     # Add missing ending square bracket if needed
-    [[ $(echo "$INLINE" | tail -c 2) = "}" ]] && INLINE+="
+    [[ $(echo "$INLINE" | tail -c 2) == "}" ]] && INLINE+="
             ]"
 
     # Request JSON
@@ -105,5 +122,5 @@ tg_sendinline() {
 
     # Post using provided request JSON
     curl -s -X POST https://api.telegram.org/bot"$TELEGRAM_TOKEN"/sendMessage \
-         -H "Content-Type: application/json" -d "$REQUEST" &> /dev/null
+        -H "Content-Type: application/json" -d "$REQUEST" &>/dev/null
 }
diff --git a/tasks/kernel-common b/tasks/kernel-common
--- a/tasks/kernel-common
+++ b/tasks/kernel-common
@@ -4,7 +4,7 @@
 # SPDX-License-Identifier: GPL-3.0-or-later
 
 # Exit if it's being executed
-if ! (return 2> /dev/null); then
+if ! (return 2>/dev/null); then
     echo "! Please source this script instead of running directly." >&2
     exit 126
 fi
@@ -23,15 +23,17 @@ get_clang-ver() {
     ROOT_DIR=/opt/kud/android
 
     case $1 in
-         5) CLANG_VERSION=4053586 ;;   # 5.0.300080
-         6) CLANG_VERSION=4691093 ;;   # 6.0.2
-         7) CLANG_VERSION=r328903 ;;   # 7.0.2
-         8) CLANG_VERSION=r349610b ;;  # 8.0.9
-         9) CLANG_VERSION=r365631c2 ;; # 9.0.8
-        10) CLANG_VERSION=r377782d ;;  # 10.0.6
-        11) CLANG_VERSION=r383902 ;;   # 11.0.1
-         *) warn "Invalid version specified!"
-            exit 1 ;;
+    5) CLANG_VERSION=4053586 ;;   # 5.0.300080
+    6) CLANG_VERSION=4691093 ;;   # 6.0.2
+    7) CLANG_VERSION=r328903 ;;   # 7.0.2
+    8) CLANG_VERSION=r349610b ;;  # 8.0.9
+    9) CLANG_VERSION=r365631c2 ;; # 9.0.8
+    10) CLANG_VERSION=r377782d ;; # 10.0.6
+    11) CLANG_VERSION=r383902 ;;  # 11.0.1
+    *)
+        warn "Invalid version specified!"
+        exit 1
+        ;;
     esac
 
     CLANG_PATH=$ROOT_DIR/clang-$CLANG_VERSION/bin
