build-clang: Use git fetch and git reset --hard for updating
release_70 was force pushed apparently, let's avoid git pull errors from now on.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Albert I <krascgq@outlook.co.id>

diff --git a/build-clang b/build-clang
--- a/build-clang
+++ b/build-clang
@@ -240,7 +240,8 @@ function git_sync() {(
             git rebase upstream/"${BRANCH}" || die "There was an error rebasing ${FOLDER}!"
         fi
     else
-        git pull || die "There was an error updating ${FOLDER}!"
+        git fetch origin || die "There was an error fetching updates for ${FOLDER}!"
+        git reset --hard origin/"${BRANCH}" || die "There was an error updating ${FOLDER}!"
     fi
 
     # Roll back if necessary
