killswitch: Add some sanity checks
Signed-off-by: Albert I <krascgq@outlook.co.id>

diff --git a/killswitch b/killswitch
--- a/killswitch
+++ b/killswitch
@@ -8,29 +8,39 @@
 # Modified to be as dead simple and minimal as possible.
 
 function die {
-    echo "! ${@}"
+    [[ -n ${1} ]] && \
+        echo "! ${1}"
+
     exit 1
 }
 
-if [[ ${#} -le 1 ]]; then
+# Do nothing on CTRL-C
+trap '' INT
+
+trap die ERR
+
+if [[ ${#} -eq 1 ]]; then
     case ${1} in
+        # Disable kill switch
         -d|--disable|off)
-            # Disable VPN kill switch
             CONFIG=( "default allow outgoing"
                      "delete allow out on tun0" ) ;;
+
+        # Enable kill switch
         -e|--enable|on)
-            # Enable VPN kill switch
             CONFIG=( "default deny outgoing"
                      "allow out on tun0" ) ;;
+
+        # Suicide
         *)
-            # Suicide
-            die "No valid option specified!" ;;
+            die "Invalid option specified!" ;;
     esac
 else
-    die "More than one option specified!"
+    die "No or more than one option specified!"
 fi
 
 for COMMAND in "${CONFIG[@]}"; do
+    # Word splitting is required here.
     # shellcheck disable=SC2086
     ufw ${COMMAND}
 done
