update_crosstool: Add support for verbosing the output
* Script is still silent by default.

Signed-off-by: Albert I <krascgq@outlook.co.id>

diff --git a/update_crosstool b/update_crosstool
--- a/update_crosstool
+++ b/update_crosstool
@@ -7,9 +7,18 @@
 BLD=$(tput bold)
 RST=$(tput sgr0)
 
+## Switches
+case ${1} in
+    -v|--verbose) VERBOSE=true ;;
+    *) # Empty values
+       VERBOSE= ;;
+esac
+
 ## Abort script when something went wrong
 function error {
     STATUS=${?}
+    [[ -z ${VERBOSE} ]] && \
+        exec 1>&5 2>&6 1> /dev/stdout 2> /dev/stderr
     echo "${BLD}! Failed to patch selected projects.${RST}"
     exit ${STATUS}
 }
@@ -49,17 +58,21 @@ function projects_list {
 
 ## Usage: update_projects "<src-dir>" "<src-branch>" "<patch-dir>"
 function update_projects {
+    ## Be quiet
+    [[ -z ${VERBOSE} ]] && \
+        exec 5>&1 6>&2 &> /dev/null
+
     ## Enter source directory
     cd "${1}" || error
 
     ## Fetch updates from upstream
-    git fetch origin "${2}" --depth=1 2> /dev/null
+    git fetch origin "${2}" --depth=1
 
     ## Hard reset current tree to latest source
-    git reset --hard FETCH_HEAD > /dev/null
+    git reset --hard FETCH_HEAD
 
     ## Clean them up as we can make mess with them at some point
-    git clean -dfx > /dev/null
+    git clean -dfx
 
     ## Fetch list of patches that we're going to apply
     if [[ ! -z "${4}" ]]; then
@@ -68,16 +81,24 @@ function update_projects {
         LIST="$(find "${3}" -name "*.patch" | sort -n)"
     fi
 
+    ## Stops here temporarily
+    [[ -z ${VERBOSE} ]] && \
+        exec 1>&5 2>&6 1> /dev/stdout 2> /dev/stderr
+
     ## Notify that project patching is about to begin
     echo "- Patching $(basename "${1}")..."
 
+    # Be quiet (again)
+    [[ -z ${VERBOSE} ]] && \
+        exec 5>&1 6>&2 &> /dev/null
+
     ## Apply crosstool-ng patches
     for PATCH in ${LIST}; do
-        # Output patch name
-        # echo "  - Applying patch $(basename "${PATCH}" | cut -d '-' -f 1 | tail -c 5)..."
+        # Output patch name if verbose
+        echo "  - Applying patch $(basename "${PATCH}" | cut -d '-' -f 1 | tail -c 5)..."
 
         # Apply every patches with merge strategy
-        patch --merge -N -s -p1 -i "${PATCH}"
+        patch --verbose --merge -N -p1 -i "${PATCH}"
     done
 
     ## Remove .orig files
@@ -87,6 +108,13 @@ function update_projects {
     # Disable shellcheck SC2164 warning as in no way this will fail.
     # shellcheck disable=SC2164
     cd - > /dev/null
+
+    # Stops here for good
+    [[ -z ${VERBOSE} ]] && \
+        exec 1>&5 2>&6 1> /dev/stdout 2> /dev/stderr
+
+    # FIXME: Script fails at very end of the function
+    return
 }
 
 variables_list
