tasks/kernel-common: Abort if unable to determine kernel version
Signed-off-by: Albert I <kras@raphielgang.org>

diff --git a/tasks/kernel-common b/tasks/kernel-common
--- a/tasks/kernel-common
+++ b/tasks/kernel-common
@@ -51,3 +51,7 @@ fi
 # Get kernel release - idea stolen from scripts/patch-kernel
 # shellcheck disable=SC1090
 source <(grep -E '^(VERSION|PATCHLEVEL)' Makefile | sed -e s/[[:space:]]//g)
+if ! [[ -n $VERSION && -n $PATCHLEVEL ]]; then
+    warn "Unable to get kernel version from Makefile!"
+    exit 1
+fi
