env/global: check_sudo: Prevent Zsh from falsely returning non-zero status
Also clean excessive lines of checking.

Test: check_sudo without arguments on both Zsh and Bash, both works
Signed-off-by: Albert I <kras@raphielgang.org>

diff --git a/env/global b/env/global
--- a/env/global
+++ b/env/global
@@ -30,14 +30,11 @@ warn() {
 # Making sure user has sudo before executing command
 check_sudo() {
     info "Checking for sudo; please enter password if prompted."
-    if [[ $(
-        sudo -v 2>/dev/null
-        echo $?
-    ) -eq 0 ]]; then
-        [[ $# != 0 ]] && sudo "$@"
-        return $?
-    elif [[ $? -eq 1 ]]; then
-        warn "Current user isn't a sudo!"
+    if ! sudo -v 2>/dev/null; then
+        warn "Current user isn't a sudoer!"
         return 1
     fi
+
+    # Prevent falsely returning non-zero status
+    if [[ $# != 0 ]]; then sudo "$@"; fi
 }
