env, snippets: Code cleanups and consistency updates
Basically a squash of these summaries:
* env/notebook: Export all needed variables at once
* env, snippets: Put warn message and return command at same line
* env: Put one-line and return commands at same line
* env: Avoid excessive use of negatives
* env: Failing on changing directories don't need custom messages
* env/notebook: parse_git_branch: Mark BRANCH as local
* env/notebook: zipsigner: Mark STATUS as local
* env/notebook: flac_repack: If (de)compress fails, output a warning
* env/notebook: zipsigner: Missed echo -> info transition

Signed-off-by: Albert I <krascgq@outlook.co.id>

diff --git a/env/notebook b/env/notebook
--- a/env/notebook
+++ b/env/notebook
@@ -20,22 +20,22 @@ export PATH=/usr/lib/ccache/bin:${PATH}
 function flac_repack {
     # Make sure FLAC package is installed
     [[ -z $(command -v flac) ]] && \
-        { warn "Please install flac package before continuing.";
-          return 1; }
+        { warn "Please install flac package before continuing."; return 1; }
 
     # Make sure we have FLAC files to repack
     [[ $(find . -name "*.flac" | wc -l) -eq 0 ]] && \
-        { warn "There's nothing to do.";
-          return 1; }
+        { warn "There's nothing to do."; return 1; }
 
-    # First we unpack
+    # First we decompress
     flac --delete-input-file --totally-silent -d ./*.flac || \
-        return 1
+        { warn "Failed to decompress one or more songs."; return 1; }
 
     # Then we repack with maximum compression and ReplayGain applied
     for SONG in ./*; do
         case "${SONG}" in
-            *.aiff|*.wav) flac --delete-input-file --totally-silent --replay-gain -V8 "${SONG}" || return 1;;
+            *.aiff|*.wav)
+                flac --delete-input-file --totally-silent --replay-gain -V8 "${SONG}" || \
+                    { warn "Failed to compress ${SONG}."; return 1; } ;;
         esac
     done
 }
@@ -44,59 +44,53 @@ function flac_repack {
 function opus_convert {
     # Ask to install opus-tools package if opusenc doesn't exist
     [[ -z $(command -v opusenc) ]] && \
-        { warn "Please install opus-tools package before continuing.";
-          return 1; }
+        { warn "Please install opus-tools package before continuing."; return 1; }
 
     for SONG in ./*; do
         case "${SONG}" in
-            *.aiff|*.flac|*.wav) # Declare that we have something to do!
-                                 SUPPORTED=true
-                                 # Not supporting wildcards for converting
-                                 opusenc --quiet --vbr --bitrate 192 --comp 10 --expect-loss 0 \
-                                     "${SONG}" \
-                                     "$(basename "${SONG}" | sed 's/\(.*\)\..*/\1/').ogg" || \
-                                     return 1 ;;
+            *.aiff|*.flac|*.wav)
+                # Declare that we have something to do!
+                SUPPORTED=true
+
+                # Not supporting wildcards for converting
+                opusenc --quiet --vbr --bitrate 192 --comp 10 --expect-loss 0 \
+                    "${SONG}" \
+                    "$(basename "${SONG}" | sed 's/\(.*\)\..*/\1/').ogg" || \
+                    return 1 ;;
         esac
     done
 
-    [[ ! ${SUPPORTED} ]] && \
-        { warn "There's nothing to do.";
-          return 1; }
+    [[ -z ${SUPPORTED} ]] && \
+        { warn "There's nothing to do."; return 1; }
 }
 
 # Wrapper to build both AArch64 and x86_64 GNU toolchains using build-tools-gcc
 function btg_build {
     [[ -z ${BTGDIR} || -z ${OPTDIR} ]] && \
-        { warn "${BLD}BTGDIR${RST} and/or ${BLD}OPTDIR${RST} variables are empty. Refusing to continue.";
-          return 1; }
+        { warn "${BLD}BTGDIR${RST} and/or ${BLD}OPTDIR${RST} variables are empty. Refusing to continue."; return 1; }
 
     (
-        ! cd "${BTGDIR}" && \
-            { warn "$(basename "${BTGDIR}") doesn't exist in defined path.";
-              return 1; }
+        cd "${BTGDIR}" || return 1
 
         # FIXME: Command requires sudo :/
         [[ ! -d ${OPTDIR} ]] && \
             sudo su -c "mkdir -p ${OPTDIR} && chown -R $(whoami):users ${OPTDIR}"
 
-        ! ./build -a arm -s gnu -v 9 -nt && \
-            return 1
+        ./build -a arm -s gnu -v 9 -nt || return 1
 
         rm -rf "${OPTDIR}"/arm-linux-gnueabi-old
         [[ -d ${OPTDIR}/arm-linux-gnueabi ]] && \
             mv -f "${OPTDIR}"/arm-linux-gnueabi{,-old}
         mv -f arm-linux-gnueabi "${OPTDIR}"
 
-        ! ./build -a arm64 -s gnu -v 9 -nt -nu && \
-            return 1
+        ./build -a arm64 -s gnu -v 9 -nt -nu || return 1
 
         rm -rf "${OPTDIR}"/aarch64-linux-gnu-old
         [[ -d ${OPTDIR}/aarch64-linux-gnu ]] && \
             mv -f "${OPTDIR}"/aarch64-linux-gnu{,-old}
         mv -f aarch64-linux-gnu "${OPTDIR}"
 
-        ! ./build -a x86_64 -s gnu -v 9 -nt -nu && \
-            return 1
+        ./build -a x86_64 -s gnu -v 9 -nt -nu || return 1
 
         rm -rf "${OPTDIR}"/x86_64-linux-gnu-old
         [[ -d ${OPTDIR}/x86_64-linux-gnu ]] && \
diff --git a/env/server b/env/server
--- a/env/server
+++ b/env/server
@@ -42,8 +42,7 @@ export PATH=${HOME}/.local/bin:${PATH}
 function ssh_setup {
     # Do an unconditional check
     [[ ! -f ${HOME}/.ssh/id_ed25519 ]] && \
-        { warn "Please generate an SSH key before using this command.";
-          return 1; }
+        { warn "Please generate an SSH key before using this command."; return 1; }
 
     # The actual setup is here
     eval "$(ssh-agent -s)"
@@ -70,61 +69,43 @@ function ct-ng_build {
 
     [[ -z $(command -v ct-ng) ]] && \
         { warn "${BLD}ct-ng${RST} isn't installed." \
-               "Please build or install crosstool-NG package before continuing.";
-          return 1; }
+               "Please build or install crosstool-NG package before continuing."; return 1; }
 
     [[ -z ${CTDIR} ]] && \
-        { warn "${BLD}CTDIR${RST} variable is empty. Refusing to continue.";
-          return 1; }
+        { warn "${BLD}CTDIR${RST} variable is empty. Refusing to continue."; return 1; }
 
     (
-        ! cd "${CTDIR}" 2> /dev/null && \
-            { warn "$(basename "${CTDIR}") doesn't exist in defined path.";
-              return 1; }
+        cd "${CTDIR}" || return 1
 
         echo "- Cleaning up work directory..."
-        ! ct-ng clean > /dev/null && \
-            { warn "Failed to clean up work directory.";
-              return 1; }
+        ct-ng clean > /dev/null || return 1
 
         (
-            ! cd "${TARDIR}" 2> /dev/null && \
-                { warn "$(basename "${CTDIR}")/$(basename "${TARDIR}") doesn't exist in defined path.";
-                  return 1; }
+            cd "${TARDIR}" || return 1
 
             [[ ! -f "gmp-6.1.99-$(check_gmp_date).tar.lz" ]] && \
                 { info "Downloading gmp-6.1.99-$(check_gmp_date).tar.lz...";
                   wget -q https://gmplib.org/download/snapshot/"gmp-6.1.99-$(check_gmp_date).tar.lz"; }
         )
         (
-            ! cd "${GITDIR}" 2> /dev/null && \
-                { warn "$(basename "${CTDIR}")/$(basename "${GITDIR}") doesn't exist in defined path.";
-                  return 1; }
+            cd "${GITDIR}" || return 1;
 
             info "Updating git projects..."
-            ./update || \
-                return 1
+            ./update || return 1
         )
         (
-            ! cd "${ISLDIR}" 2> /dev/null && \
-                { warn "$(basename "${CTDIR}")/$(basename "${GITDIR}")/$(basename "${ISLDIR}") doesn't exist in defined path.";
-                  return 1; }
+            cd "${ISLDIR}" || return 1;
 
             [[ ! -d .git ]] && \
                 { warn "$(basename "${CTDIR}")/$(basename "${GITDIR}")/$(basename "${ISLDIR}") isn't a git project." \
-                       "Are you sure the defined path is correct?";
-                  return 1; }
+                       "Are you sure the defined path is correct?"; return 1; }
 
             info "Regenerating ISL configuration files..."
             git clean -dfx > /dev/null
-            ! ./autogen.sh && \
-                { warn "Failed to generate configuration files.";
-                  return 1; }
+            ./autogen.sh || return 1
         )
 
-        ! ct-ng source && \
-            { warn "Failed to obtain required sources.";
-              return 1; }
+        ct-ng source || return 1;
 
         if ct-ng build; then
             echo
@@ -142,23 +123,19 @@ function update_binaries {
     (
         # Check if ${GOPATH} is defined and exist
         [[ -z ${GOPATH} || ! -d ${GOPATH} ]] && \
-            { warn "GOPATH doesn't seem to be defined or exist.";
-              return 1; }
+            { warn "GOPATH doesn't seem to be defined or exist."; return 1; }
 
         # Fetch or update required projects
         info "Fetching Caddy sources..."
         for PROJECTS in mholt/caddy/caddy caddyserver/builds; do
             go get -u github.com/${PROJECTS} || \
-                { warn "Failed to fetch ${PROJECTS}.";
-                  return 1; }
+                { warn "Failed to fetch ${PROJECTS}."; return 1; }
         done
 
         # Build from source
         info "Building Caddy..."
-        cd ${GOPATH}/src/github.com/mholt/caddy/caddy || \
-            return 1
-        go run build.go || \
-            return 1
+        cd ${GOPATH}/src/github.com/mholt/caddy/caddy || return 1
+        go run build.go || return 1
     )
 
     # Done!
