env/notebook: Replace '--totally-silent' with '-s' on flac arguments
FLAC 1.3.3 doesn't warn about compressing 24-bit legacy WAVE audio
anymore, so we can re-enable default silent behavior to help catching
errors.

Signed-off-by: Albert I <kras@raphielgang.org>

diff --git a/env/notebook b/env/notebook
--- a/env/notebook
+++ b/env/notebook
@@ -73,7 +73,7 @@ flac_pack() {
         # Unpack FLAC files
         for SONG in "${LIST[@]}"; do
             info "Unpacking \"$SONG\"..."
-            flac --delete-input-file --totally-silent -d "$SONG" || { warn "Failed to unpack \"$SONG\"."; return 1; }
+            flac --delete-input-file -s -d "$SONG" || { warn "Failed to unpack \"$SONG\"."; return 1; }
         done
     fi
 
@@ -119,7 +119,7 @@ flac_pack() {
     # Pack PCM audio files with maximum compression
     for SONG in "${LIST[@]}"; do
         info "Packing \"$SONG\"..."
-        flac --delete-input-file --totally-silent -V8 "$SONG" || { warn "Failed to pack \"$SONG\"."; return 1; }
+        flac --delete-input-file -s -V8 "$SONG" || { warn "Failed to pack \"$SONG\"."; return 1; }
     done
 
     # Embed ReplayGain if requested
